all:	program1	program2	program3

clean:
	rm -f *.o boring.c custom.c multi.c

program1:	boring.c
	gcc -o boring boring.c
program2:	custom.c
	gcc -o custom custom.c
program3:	multi.c
	gcc -o multi multi.c
